### ISSUE TITLE
Lofi04 and Games04 don't play

### ISSUE THREAD

**Issue by ryan-lumos** [LIONisaQT/chill-mood-club#6]
Invalid playlists maybe?

**Comment by LIONisaQT** [comment]
[Both](https://www.youtube.com/watch?v=MO30O_f1nzU) [videos](https://www.youtube.com/watch?v=Q326lVMgsHkl) are unavailable RIP LMAO.

**Comment by LIONisaQT** [comment]
Titles and playlists have been updated.

[Sheets link](https://docs.google.com/spreadsheets/d/18DfByBtJQTPjT7m0Tm7hj6cMdBF_TU8SAmMw7ZsIN9I/edit?pli=1#gid=0).

**Comment by LIONisaQT** [comment]
Resolved with b19d469442ad124481897c33d7990368571fdf06...for now 👀
